name: Setup Node.js (v20) with Yarn v2 🚀
description: Set up Node.js version 20 and enable Yarn v2 using Corepack

inputs:
  node-version:
    description: The version of Node.js to set up.
    required: true
    default: '20'

outputs:
  node-version:
    description: The version of Node.js that was installed.

runs:
  using: composite
  steps:
    - name: Set up Node.js v${{ inputs.node-version }} 💻
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Yarn v2 ⚡️
      run: |
        corepack enable
        yarn --version
        node --version
      shell: bash
